In [1]:
import numpy as np
from statistics import mode

In [2]:
#Load the problem
fp = np.load('./problems/gbs_exp1_part1.npz')

In [3]:
dataset = fp['arr_0']
shuffle_row_idx = fp['arr_1']
shuffle_col_idx = fp['arr_2']
bicluster_row_idx = fp['arr_3']
bicluster_col_idx = fp['arr_4']

In [4]:
def list_to_str(l):
    
    temp_str = str(l)
    temp_str = temp_str.replace("[","")
    temp_str = temp_str.replace("]","")
    temp_str = temp_str.replace(",","")
    temp_str = temp_str.replace(" ","")
    return temp_str

In [5]:
#Create bicluster_string
bicluster_list = [0 for i in range(2*dataset.shape[0])]

#rows
for item in np.sort(bicluster_row_idx[:,0]):
    bicluster_list[item] = 1

#columns
for item in np.sort(bicluster_col_idx[:,0]):
    bicluster_list[item + dataset.shape[0]] = 1

bicluster_str = list_to_str(bicluster_list)
print("The ideal bicluster string would be:", bicluster_str)

The ideal bicluster string would be: 001110111000001100101011


In [6]:
all_photons = [i * 24 for i in [1,2,4,6,10]]
all_shots = [1000,10000]

In [7]:
for photon in all_photons:
    for shots in all_shots:
        filepath = './results/res_gbs_exp1_photon'+str(photon)+'_shots'+str(shots)+'.npy'
        raw_samples = np.load(filepath)
        string_samples = []
        for list in raw_samples: 
            string_samples.append(list_to_str(list))
        majority_string = mode(string_samples)
        print(f"shots: {shots}, photons per mode: {photon/(2*dataset.shape[0])}")
        is_majority_correct = (majority_string == bicluster_str)
        print("Correct sample majority?:",is_majority_correct)
        print("Count of correct sample:",string_samples.count(bicluster_str))
        print("Correct sample probability:", string_samples.count(bicluster_str) / shots)
        
        print("----")

shots: 1000, photons per mode: 1.0
Correct sample majority?: False
Count of correct sample: 79
Correct sample probability: 0.079
----
shots: 10000, photons per mode: 1.0
Correct sample majority?: False
Count of correct sample: 735
Correct sample probability: 0.0735
----
shots: 1000, photons per mode: 2.0
Correct sample majority?: True
Count of correct sample: 97
Correct sample probability: 0.097
----
shots: 10000, photons per mode: 2.0
Correct sample majority?: True
Count of correct sample: 1038
Correct sample probability: 0.1038
----
shots: 1000, photons per mode: 4.0
Correct sample majority?: True
Count of correct sample: 107
Correct sample probability: 0.107
----
shots: 10000, photons per mode: 4.0
Correct sample majority?: True
Count of correct sample: 1099
Correct sample probability: 0.1099
----
shots: 1000, photons per mode: 6.0
Correct sample majority?: True
Count of correct sample: 115
Correct sample probability: 0.115
----
shots: 10000, photons per mode: 6.0
Correct sample maj

In [8]:
#Now lets see the results for the binary dataset

In [9]:
for photon in all_photons:
    for shots in all_shots:
        filepath = './results/resbin_gbs_exp1_photon'+str(photon)+'_shots'+str(shots)+'.npy'
        raw_samples = np.load(filepath)
        string_samples = []
        for list in raw_samples: 
            string_samples.append(list_to_str(list))
        majority_string = mode(string_samples)
        print(f"shots: {shots}, photons per mode: {photon/(2*dataset.shape[0])}")
        is_majority_correct = (majority_string == bicluster_str)
        print("Correct sample majority?:",is_majority_correct)
        print("Count of correct sample:",string_samples.count(bicluster_str))
        print("Correct sample probability:", string_samples.count(bicluster_str) / shots)
        
        print("----")

shots: 1000, photons per mode: 1.0
Correct sample majority?: True
Count of correct sample: 186
Correct sample probability: 0.186
----
shots: 10000, photons per mode: 1.0
Correct sample majority?: True
Count of correct sample: 1949
Correct sample probability: 0.1949
----
shots: 1000, photons per mode: 2.0
Correct sample majority?: True
Count of correct sample: 428
Correct sample probability: 0.428
----
shots: 10000, photons per mode: 2.0
Correct sample majority?: True
Count of correct sample: 4125
Correct sample probability: 0.4125
----
shots: 1000, photons per mode: 4.0
Correct sample majority?: True
Count of correct sample: 647
Correct sample probability: 0.647
----
shots: 10000, photons per mode: 4.0
Correct sample majority?: True
Count of correct sample: 6180
Correct sample probability: 0.618
----
shots: 1000, photons per mode: 6.0
Correct sample majority?: True
Count of correct sample: 724
Correct sample probability: 0.724
----
shots: 10000, photons per mode: 6.0
Correct sample maj

In [11]:
raw_samples

array([[0., 0., 1., ..., 0., 1., 1.],
       [0., 0., 1., ..., 0., 1., 1.],
       [0., 0., 1., ..., 0., 1., 1.],
       ...,
       [0., 0., 1., ..., 0., 1., 1.],
       [0., 0., 1., ..., 0., 1., 1.],
       [0., 0., 1., ..., 0., 1., 1.]])

In [12]:
#debugging something, remove afterwards
photons = 24
shots = 1000
filepath = './results/resbin_gbs_exp1_photon'+str(photon)+'_shots'+str(shots)+'.npy'
s1 = np.load(filepath)

photons = 24
shots = 10000
filepath = './results/resbin_gbs_exp1_photon'+str(photon)+'_shots'+str(shots)+'.npy'
s2 = np.load(filepath)


In [13]:
s1

array([[0, 0, 1, ..., 0, 1, 1],
       [0, 0, 1, ..., 0, 1, 1],
       [0, 0, 1, ..., 0, 1, 1],
       ...,
       [0, 0, 1, ..., 0, 1, 1],
       [0, 0, 1, ..., 0, 1, 1],
       [0, 0, 1, ..., 0, 1, 1]], dtype=int64)

In [14]:
s2

array([[0., 0., 1., ..., 0., 1., 1.],
       [0., 0., 1., ..., 0., 1., 1.],
       [0., 0., 1., ..., 0., 1., 1.],
       ...,
       [0., 0., 1., ..., 0., 1., 1.],
       [0., 0., 1., ..., 0., 1., 1.],
       [0., 0., 1., ..., 0., 1., 1.]])