In [1]:
import numpy as np

arange is like range that creates a numpy array

In [2]:
x = np.arange(1,17,)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

arange can be incremented in float!

In [3]:
x = np.arange(1,17,0.2)
x

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8,
       12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. ,
       14.2, 14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2,
       16.4, 16.6, 16.8])

I can 'reshape' my uni-dimensional np array into other shape. In this case, this is a matrix:

In [4]:
x =np.arange(1,17).reshape((4,4))
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

I want to access the first element (row 0 col 0)

In [5]:
x[0,0]

1

 (row 0 col 1)

In [6]:
x[0,1]

2

Select a column (slicing across all the rows)

In [7]:
x[:,2]

array([ 3,  7, 11, 15])

Select a row (slicing across all the columns)

In [8]:
x[2,:]

array([ 9, 10, 11, 12])

Selecting a sub-matrix from x

In [9]:
x[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [10]:
x[2:4,2:4]

array([[11, 12],
       [15, 16]])

Access multiple items from the matrix

In [11]:
x[(2,1),(2,3)]

array([11,  8])

Access non-contiguous rows and columns from the Matrix x

In [14]:
rows = [0,3]
cols = [1,2]
x[np.ix_(rows, cols)]

array([[ 2,  3],
       [14, 15]])

In [15]:
np.ix_(rows, cols)

(array([[0],
        [3]]),
 array([[1, 2]]))

In [13]:
l = [[1,2],[3,4],[5,6]]

In [17]:
a1 = np.array([0,1,1,3])


In [18]:
all( i < 4 for i in a1)

True