In [1]:
import numpy as np

In [2]:
#Boson sampling
#Experiment 2
#Dataset size is 12 x 12
#bicluster size is 6 x 6

In [3]:
#Idea : (1) We will take bs_exp1_part1.npy load it and (2) then reshuffle the rows and columns  (3) save it as a new npz file with columns and rows 

In [4]:
#Load  bs_exp1_part1.npy 
dataset = np.load('./problems/bs_exp1_part1.npy')
dataset

array([[0.2, 0.1, 0.2, 0.2, 0.1, 0.2, 0.2, 0.2, 0.1, 0. , 0. , 0. ],
       [0.1, 0. , 0.1, 0.1, 0.1, 0.1, 0.2, 0. , 0.2, 0.1, 0.1, 0. ],
       [0.1, 0.2, 0. , 0.2, 0. , 0.1, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.2, 0.2, 0.2, 0.7, 0.7, 0.8, 0.8, 0.9, 0.9, 0. , 0.2, 0. ],
       [0.2, 0.2, 0.2, 0.7, 0.8, 0.7, 0.9, 0.8, 0.7, 0.2, 0.1, 0. ],
       [0. , 0. , 0.2, 0.8, 0.9, 0.9, 0.7, 0.9, 0.7, 0.1, 0.2, 0.1],
       [0.1, 0.2, 0. , 0.7, 0.7, 0.9, 0.9, 0.8, 0.8, 0.2, 0.2, 0.2],
       [0.1, 0. , 0. , 0.8, 0.7, 0.8, 0.7, 0.9, 0.7, 0.1, 0. , 0.1],
       [0.1, 0.1, 0. , 0.7, 0.8, 0.7, 0.9, 0.8, 0.7, 0.1, 0.1, 0. ],
       [0.1, 0.1, 0.2, 0. , 0. , 0.1, 0. , 0.1, 0. , 0.2, 0.2, 0.1],
       [0.1, 0. , 0. , 0. , 0. , 0.1, 0. , 0. , 0.1, 0.2, 0.1, 0.2],
       [0.1, 0.2, 0. , 0. , 0.1, 0. , 0. , 0.1, 0.2, 0.2, 0.1, 0.1]])

In [5]:
np.random.seed(108)
col_idx = np.random.permutation(12)
row_idx = np.random.permutation(12)

bicluster_old_idx = [3,4,5,6,7,8] #for both row and columns
bicluster_col_idx = []
bicluster_row_idx = []

#Locate the columns and rows of the bicluster
#for both bicluster_row_idx and bicluster_col_idx: first column is idx position in new dataset, second is idx position in old dataset
for i in range(0,len(col_idx)):
    if col_idx[i] in bicluster_old_idx:
        bicluster_col_idx.append([i, col_idx[i]])
    if row_idx[i] in bicluster_old_idx:
        bicluster_row_idx.append([i, row_idx[i]])


print(col_idx)
print(row_idx)
print(f"Bicluster is in cols: {bicluster_col_idx}, rows: {bicluster_row_idx}")

[11  0  5  8  9 10  4  2  6  1  7  3]
[11 10  3  5  8  0  7  6  4  2  1  9]
Bicluster is in cols: [[2, 5], [3, 8], [6, 4], [8, 6], [10, 7], [11, 3]], rows: [[2, 3], [3, 5], [4, 8], [6, 7], [7, 6], [8, 4]]


In [6]:
#sort according to second column of  bicluster_col_idx
bicluster_col_idx = np.array(bicluster_col_idx)
bicluster_col_idx = bicluster_col_idx[bicluster_col_idx[:, 1].argsort()]
bicluster_col_idx

array([[11,  3],
       [ 6,  4],
       [ 2,  5],
       [ 8,  6],
       [10,  7],
       [ 3,  8]])

In [7]:
#sort according to second row of  bicluster_col_idx
bicluster_row_idx = np.array(bicluster_row_idx)
bicluster_row_idx = bicluster_row_idx[bicluster_row_idx[:, 1].argsort()]
bicluster_row_idx

array([[2, 3],
       [8, 4],
       [3, 5],
       [7, 6],
       [6, 7],
       [4, 8]])

In [8]:
#Now for the actual shuffling
#Shuffle the columns of dataset and copy it to new_dataset
new_dataset = dataset[:,col_idx].copy()
new_dataset

array([[0. , 0.2, 0.2, 0.1, 0. , 0. , 0.1, 0.2, 0.2, 0.1, 0.2, 0.2],
       [0. , 0.1, 0.1, 0.2, 0.1, 0.1, 0.1, 0.1, 0.2, 0. , 0. , 0.1],
       [0. , 0.1, 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0.2, 0. , 0.2],
       [0. , 0.2, 0.8, 0.9, 0. , 0.2, 0.7, 0.2, 0.8, 0.2, 0.9, 0.7],
       [0. , 0.2, 0.7, 0.7, 0.2, 0.1, 0.8, 0.2, 0.9, 0.2, 0.8, 0.7],
       [0.1, 0. , 0.9, 0.7, 0.1, 0.2, 0.9, 0.2, 0.7, 0. , 0.9, 0.8],
       [0.2, 0.1, 0.9, 0.8, 0.2, 0.2, 0.7, 0. , 0.9, 0.2, 0.8, 0.7],
       [0.1, 0.1, 0.8, 0.7, 0.1, 0. , 0.7, 0. , 0.7, 0. , 0.9, 0.8],
       [0. , 0.1, 0.7, 0.7, 0.1, 0.1, 0.8, 0. , 0.9, 0.1, 0.8, 0.7],
       [0.1, 0.1, 0.1, 0. , 0.2, 0.2, 0. , 0.2, 0. , 0.1, 0.1, 0. ],
       [0.2, 0.1, 0.1, 0.1, 0.2, 0.1, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.1, 0.1, 0. , 0.2, 0.2, 0.1, 0.1, 0. , 0. , 0.2, 0.1, 0. ]])

In [9]:
#Shuffle the rows of new_dataset
new_dataset = new_dataset[row_idx,:]
new_dataset

array([[0.1, 0.1, 0. , 0.2, 0.2, 0.1, 0.1, 0. , 0. , 0.2, 0.1, 0. ],
       [0.2, 0.1, 0.1, 0.1, 0.2, 0.1, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.2, 0.8, 0.9, 0. , 0.2, 0.7, 0.2, 0.8, 0.2, 0.9, 0.7],
       [0.1, 0. , 0.9, 0.7, 0.1, 0.2, 0.9, 0.2, 0.7, 0. , 0.9, 0.8],
       [0. , 0.1, 0.7, 0.7, 0.1, 0.1, 0.8, 0. , 0.9, 0.1, 0.8, 0.7],
       [0. , 0.2, 0.2, 0.1, 0. , 0. , 0.1, 0.2, 0.2, 0.1, 0.2, 0.2],
       [0.1, 0.1, 0.8, 0.7, 0.1, 0. , 0.7, 0. , 0.7, 0. , 0.9, 0.8],
       [0.2, 0.1, 0.9, 0.8, 0.2, 0.2, 0.7, 0. , 0.9, 0.2, 0.8, 0.7],
       [0. , 0.2, 0.7, 0.7, 0.2, 0.1, 0.8, 0.2, 0.9, 0.2, 0.8, 0.7],
       [0. , 0.1, 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0.2, 0. , 0.2],
       [0. , 0.1, 0.1, 0.2, 0.1, 0.1, 0.1, 0.1, 0.2, 0. , 0. , 0.1],
       [0.1, 0.1, 0.1, 0. , 0.2, 0.2, 0. , 0.2, 0. , 0.1, 0.1, 0. ]])

In [10]:
#Extract the bicluster from the new_dataset based on the idx values in bicluster_row_idx and bicluster_col_idx
new_dataset[np.ix_(bicluster_row_idx[:,0], bicluster_col_idx[:,0])]

array([[0.7, 0.7, 0.8, 0.8, 0.9, 0.9],
       [0.7, 0.8, 0.7, 0.9, 0.8, 0.7],
       [0.8, 0.9, 0.9, 0.7, 0.9, 0.7],
       [0.7, 0.7, 0.9, 0.9, 0.8, 0.8],
       [0.8, 0.7, 0.8, 0.7, 0.9, 0.7],
       [0.7, 0.8, 0.7, 0.9, 0.8, 0.7]])

In [11]:
dataset[3:9,3:9] #just to check if the bicluster in the original dataset is the same

array([[0.7, 0.7, 0.8, 0.8, 0.9, 0.9],
       [0.7, 0.8, 0.7, 0.9, 0.8, 0.7],
       [0.8, 0.9, 0.9, 0.7, 0.9, 0.7],
       [0.7, 0.7, 0.9, 0.9, 0.8, 0.8],
       [0.8, 0.7, 0.8, 0.7, 0.9, 0.7],
       [0.7, 0.8, 0.7, 0.9, 0.8, 0.7]])

In [12]:
#Sanity check ||old_bicluster - shuffledbicluster|| --> 0
np.linalg.norm(new_dataset[np.ix_(bicluster_row_idx[:,0], bicluster_col_idx[:,0])] - dataset[3:9,3:9])

0.0

In [13]:
#Now save it to the npz
#arr_0 : new_dataset
#arr_1 : row_idx
#arr_2 : col_idx
#arr_3 : bicluster_row_idx
#arr_4 : bicluster_col_idx
np.savez('./problems/bs_exp2_part1.npz',new_dataset,row_idx,col_idx,bicluster_row_idx,bicluster_col_idx)