In [1]:
#Take the first problem, remove two biclusters (#1 and #2) and save it as part 2
import numpy as np

In [2]:
#Load the problem
fp = np.load('./problems/gbs_exp2_part1.npz')

In [3]:
dataset = fp['arr_0']
shuffle_row_idx = fp['arr_1']
shuffle_col_idx = fp['arr_2']
biclusters_row_idx = fp['arr_3']
biclusters_col_idx = fp['arr_4']

In [4]:
dataset

array([[0.2, 0. , 0.7, 0.2, 0.1, 0.8, 0. , 0.9, 0.2, 0.7, 0. , 0.2],
       [0.2, 0. , 0.9, 0.2, 0.1, 0.8, 0. , 0.8, 0.2, 0.7, 0. , 0. ],
       [0.1, 0.7, 0.2, 0.1, 0. , 0. , 0.7, 0.2, 0.1, 0.2, 0.8, 0.8],
       [0.1, 0.8, 0.2, 0.1, 0.1, 0.1, 0.9, 0. , 0.2, 0.2, 0.7, 0.9],
       [0.2, 0.9, 0. , 0.2, 0.1, 0.2, 0.9, 0.1, 0.1, 0.1, 0.8, 0.7],
       [0.9, 0.2, 0.2, 0.7, 0.8, 0.1, 0.2, 0.2, 0.7, 0.2, 0. , 0. ],
       [0.1, 0.7, 0.2, 0.2, 0.1, 0.2, 0.9, 0. , 0. , 0. , 0.7, 0.8],
       [0.8, 0. , 0.2, 0.8, 0.7, 0.1, 0. , 0. , 0.7, 0.1, 0.1, 0.2],
       [0.1, 0.2, 0.9, 0. , 0.2, 0.7, 0.1, 0.9, 0.2, 0.7, 0. , 0.1],
       [0.9, 0. , 0.2, 0.7, 0.7, 0. , 0.2, 0.2, 0.7, 0.1, 0. , 0.2],
       [0.9, 0.1, 0. , 0.8, 0.8, 0.2, 0. , 0.2, 0.9, 0. , 0.1, 0.2],
       [0.1, 0.1, 0.8, 0.1, 0.1, 0.7, 0. , 0.9, 0. , 0.7, 0. , 0. ]])

In [5]:
#Set bicluster #1 and #2 to zero
for i in range(1,3):
    dataset[np.ix_(np.sort(biclusters_row_idx[i][:,0]),np.sort(biclusters_col_idx[i][:,0]))] = np.zeros([4,4])

In [9]:
np.savez('./problems/gbs_exp2_part2.npz',dataset,shuffle_row_idx,shuffle_col_idx,biclusters_row_idx[0],biclusters_col_idx[0])

In [16]:
np.sort(biclusters_row_idx[0][:,0])

array([2, 3, 4, 6])

In [17]:
np.sort(biclusters_col_idx[0][:,0])

array([ 1,  6, 10, 11])

In [10]:
dataset

array([[0.2, 0. , 0. , 0.2, 0.1, 0. , 0. , 0. , 0.2, 0. , 0. , 0.2],
       [0.2, 0. , 0. , 0.2, 0.1, 0. , 0. , 0. , 0.2, 0. , 0. , 0. ],
       [0.1, 0.7, 0.2, 0.1, 0. , 0. , 0.7, 0.2, 0.1, 0.2, 0.8, 0.8],
       [0.1, 0.8, 0.2, 0.1, 0.1, 0.1, 0.9, 0. , 0.2, 0.2, 0.7, 0.9],
       [0.2, 0.9, 0. , 0.2, 0.1, 0.2, 0.9, 0.1, 0.1, 0.1, 0.8, 0.7],
       [0. , 0.2, 0.2, 0. , 0. , 0.1, 0.2, 0.2, 0. , 0.2, 0. , 0. ],
       [0.1, 0.7, 0.2, 0.2, 0.1, 0.2, 0.9, 0. , 0. , 0. , 0.7, 0.8],
       [0. , 0. , 0.2, 0. , 0. , 0.1, 0. , 0. , 0. , 0.1, 0.1, 0.2],
       [0.1, 0.2, 0. , 0. , 0.2, 0. , 0.1, 0. , 0.2, 0. , 0. , 0.1],
       [0. , 0. , 0.2, 0. , 0. , 0. , 0.2, 0.2, 0. , 0.1, 0. , 0.2],
       [0. , 0.1, 0. , 0. , 0. , 0.2, 0. , 0.2, 0. , 0. , 0.1, 0.2],
       [0.1, 0.1, 0. , 0.1, 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. ]])

In [18]:
f = np.load('./problems/gbs_exp2_part2.npz')

In [19]:
f['arr_0']

array([[0.2, 0. , 0. , 0.2, 0.1, 0. , 0. , 0. , 0.2, 0. , 0. , 0.2],
       [0.2, 0. , 0. , 0.2, 0.1, 0. , 0. , 0. , 0.2, 0. , 0. , 0. ],
       [0.1, 0.7, 0.2, 0.1, 0. , 0. , 0.7, 0.2, 0.1, 0.2, 0.8, 0.8],
       [0.1, 0.8, 0.2, 0.1, 0.1, 0.1, 0.9, 0. , 0.2, 0.2, 0.7, 0.9],
       [0.2, 0.9, 0. , 0.2, 0.1, 0.2, 0.9, 0.1, 0.1, 0.1, 0.8, 0.7],
       [0. , 0.2, 0.2, 0. , 0. , 0.1, 0.2, 0.2, 0. , 0.2, 0. , 0. ],
       [0.1, 0.7, 0.2, 0.2, 0.1, 0.2, 0.9, 0. , 0. , 0. , 0.7, 0.8],
       [0. , 0. , 0.2, 0. , 0. , 0.1, 0. , 0. , 0. , 0.1, 0.1, 0.2],
       [0.1, 0.2, 0. , 0. , 0.2, 0. , 0.1, 0. , 0.2, 0. , 0. , 0.1],
       [0. , 0. , 0.2, 0. , 0. , 0. , 0.2, 0.2, 0. , 0.1, 0. , 0.2],
       [0. , 0.1, 0. , 0. , 0. , 0.2, 0. , 0.2, 0. , 0. , 0.1, 0.2],
       [0.1, 0.1, 0. , 0.1, 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. ]])